crm/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customerservice.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

urlpatterns += [
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
]

customerservice/urls.py
from django.urls import path, re_path
# from django.conf.urls import url
from . import views

app_name = 'customerservice'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('customers/', views.CustomerListView.as_view(), name='customers'),
    # re_path(r'^customer/(?P<pk>\d+)$', views.CustomerDetailView.as_view(), name='customer-detail'),
    # path('customer/<int:pk>', views.CustomerDetailView.as_view(), name='customer-detail'),
    path('customer/<int:pk>', views.customer_details_with_agent, name='customer-detail-with-agent'),
    path('customer/create', views.CustomerCreate.as_view(), name='customer_create'),
    path('agent/create', views.AgentCreate.as_view(), name='agent_create'),
    # path('customer/create', views.CustomerCreateView.as_view(), name='customer_form'),
    path('customer/<int:pk>/agents/edit/', views.CustmerAgentsEditView.as_view(), name='customer_agent_edit'),

    

]

customerservice/models.py
from cProfile import label
from email.headerregistry import Address
from pyexpat import model
from django.db import models
from django.urls import reverse
# from django.forms import ModelForm

class Customer(models.Model):
    commercialname = models.CharField(max_length=50, blank=False, null=False)
    brand = models.CharField(max_length=25, blank=False, null=False)
    # city = models.CharField(max_length=15, blank=False, null= False)
    address = models.CharField(max_length=100, blank=True, null=True)
    
    def __str__(self):
        return '%s (%s)' % (self.commercialname,self.brand)
        # return self.commercialname
        
    def commercialname_brand(self): #To display in list_display at Adminmodel
        return '%s (%s)' % (self.commercialname,self.brand)
    commercialname_brand.short_description = 'Commercial Name (Brand)'
    
    # def get_absolute_url(self):
    #     return reverse("customerservice/customer-detail", args=[str(self.id)])
        
    def get_absolute_url(self):
        # return reverse('customerservice:customer-detail', args=[str(self.id)])
        return reverse('customerservice:customer-detail-with-agent', args=[str(self.id)])
        
    # def display_agent_number(self):
    #     return ', '.join([genre.name for genre in self.genre.all()[:3]])
    #  display_agent_number.short_description = 'Genre'   
        
class Agent(models.Model):
    name = models.CharField(max_length=25, verbose_name='نام و نام خانوادگی')
    email = models.EmailField(verbose_name='ایمیل')
    phone = models.CharField(max_length=11, verbose_name='تلفن')
    mobile = models.CharField(max_length=11, verbose_name='تلفن همراه')
    rolechoices = (
        ('tec', 'فنی'),
        ('com', 'بازرگانی'),
        ('leg', 'حقوقی'),
    )
    role = models.CharField(max_length=3, choices= rolechoices, default='tec', verbose_name='نقش نماینده')
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name='نام مشترک')
    # class Meta:
    #     ordering 
    
    def related_customer(self):         #To display in list_display at Adminmodel
        return '%s (%s)' % (self.customer.commercialname,self.customer.brand)
        
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('customerservice:customer-detail-with-agent', args=[str(self.id)])
    
class Wireless(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=False, null=False)
    popsite_choices = (
        ('بوتان', 'بوتان'),
        ('شریعتی', 'شریعتی'),
        ('زرین', 'زرین'),
        ('کردستان', 'کردستان'),
        ('سنایی', 'سنایی'),
        ('پلاستیران', 'پلاستیران'),
    )
    popsite = models.CharField(max_length=25, choices=popsite_choices, blank=False, null=False)
    # t stands for transmit, r for recieve
    internet_t_bw = models.BigIntegerField(blank=True, null=True)
    internet_r_bw = models.BigIntegerField(blank=True, null=True)
    interanet_t_bw = models.BigIntegerField(blank=True, null=True)
    interanet_r_bw = models.BigIntegerField(blank=True, null=True)
    throughput_t_bw = models.BigIntegerField(blank=True, null=True)
    throughput_r_bw = models.BigIntegerField(blank=True, null=True)
    notes = models.CharField(max_length=500)
    
class Cloud(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=False, null=False)
    sizechoices = (
        ('micro', 'Micro'),
        ('small', 'Small'),
        ('medium', 'Medium'),
        ('large', 'Large'),
        ('xlarge', 'XLarge'),
        ('xxlarge', 'XXLarge'),
    )
    size = models.CharField(max_length=7, choices=sizechoices, default='medium', blank=False, null=False)
    

# class CustomerForm(ModelForm):
#     class Meta:
#         model = Customer
#         fields = '__all__'
#         # fields = ['commercialname', 'brand']    

customerservice/forms.py
from dataclasses import fields
import imp
from pyexpat import model
from socket import fromshare
from tkinter import Widget
# from django import froms
from .models import Customer, Agent
# from . import models
from django.forms import ModelForm
from django.forms.models import inlineformset_factory, InlineForeignKeyField
from django.core.exceptions import ValidationError
# from django.utils.translation import ugettext_lazy as _


CustomerAgentsFormset = inlineformset_factory(Customer, Agent, fields=('name', 'email', 'phone', 'mobile', 'role', 'customer'),extra= 2, can_delete=True)

# class CustomerForm(ModelForm):
#     class Meta:
#         model = Customer
#         # fields = '__all__'
#         fields = ['commercialname', 'brand', ]
#         # Widget = 

# class AgentForm(ModelForm):
#     class Meta:
#         model = Agent
#         fields = '__all__'

# AgentInlineFormset = inlineformset_factory(Customer, Agent,form=AgentForm, extra=1, can_delete=True)

customerservice/views.py
from cProfile import label
from email import message
from http.client import HTTPResponse
from multiprocessing import context
from tkinter import Label
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.http import HttpResponseRedirect
from . import models
from django.template.loader import render_to_string
from django.db import transaction
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import CreateView, UpdateView, DeleteView, FormView
from extra_views import FormSetView
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from django.forms import modelformset_factory
from django.views.generic.detail import SingleObjectMixin
# from .forms import CustomerForm, AgentForm, AgentInlineFormset
from .forms import CustomerAgentsFormset

# @login_required
# def index(request):
#     num_customer = models.Customer.objects.all().count()
#     num_agent = models.Agent.objects.all().count()
#     context = {'num_customer' : num_customer, 'num_agent' : num_agent}
#     return render(request, 'index.html', context)

class Index(LoginRequiredMixin, generic.TemplateView):
    login_url = '/accounts/login/'
    template_name = 'index.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_customers'] = models.Customer.objects.all()[:5]
        context = {'num_customer' : models.Customer.objects.all().count(), 'num_agent' : models.Agent.objects.all().count()}
        return context


class CustomerListView(LoginRequiredMixin, generic.ListView):
    #name of class: ClassnameListView / name of list that is sent to template: classname_list
    #name of template_name we must create for it: classname_list.html
    model = models.Customer #template_name = customer_list.html context = customer_list
    # context_object_name = 'my_customer_list'
    # queryset = models.Customer.objects.filter(brand__icontains = 'thing')
    # def  get_queryset(self):
    #     return models.Customer.objects.filter(brand__icontains = 'thing')[:5]
    template_name = 'customer_list.html'
    login_url = '/accounts/login/'
    # redirect_field_name = ''

    
class CustomerDetailView(generic.DetailView):# min 10
    model = models.Customer 
    # model: [models.Customer,models.Agent]
    template_name = 'customer_detail.html'
    # context = {}
    # def get_context_data(self, **kwargs):
    #     # Call the base implementation first to get a context
    #     context = super().get_context_data(**kwargs)
    #     # Add in a QuerySet of all the books
    #     context['book_list'] = Book.objects.all()
    #     return context
    
    
    
    
    # template_name = 'customerservice/customer_detail.html'
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs) 
    #     # context['now'] = timezone.now()
    #     context = {'customer' : models.Customer.objects.all().count()}
    #     return context
    # template_name = 'customerservice:customer_detail.html'
    #name of class: ClassnameDetailView
    #name of list that is sent to template: classname
    #name of template_name we must create for it: classname_detail.html
    
    # template_name = 'custoasdasdmer_detail.html'
    
    
    #get-query-set
    #default template-name= Classname_List
    #context_object_name: Optional[str] your own name for the list as a template variable
    
    # def get_queryset(self) -> _SupportsPagination[_M]:  
    #     return super().get_queryset()
    
    # def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
    #     return super().get_context_data(**kwargs)
    
def customer_details_with_agent(request, pk):
    # template_name = 'customer_details_with_agent'
    customer = models.Customer.objects.get(id=pk)
    # agent = models.Agent.objects.all().count()
    agent = customer.agent_set.all()
    # customer.get_queryset(self)  
    context = {'customer' : customer, 'agent': agent}
    # context = {'customer' : customer}
    return render(request, 'customer_details_with_agent.html', context)

class CustomerCreate(CreateView):
    model = models.Customer
    fields = '__all__'
    template_name = 'customer_form.html'
    # initial = {'':}
    # success_url = reverse_lazy('customerservice:customers')

class AgentCreate(CreateView):
    model = models.Agent
    fields = '__all__'
    template_name = 'agent_form.html'

class CustmerAgentsEditView (SingleObjectMixin, FormView):
    model = models.Agent
    template_name = 'customer_agents_edit.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=models.Customer.objects.all())
        # object.fields[].label='حذف'
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=models.Customer.objects.all())
        return super().post(request, *args, **kwargs)
    
    def get_form(self, form_class=None):
        return CustomerAgentsFormset(**self.get_form_kwargs(), instance=self.object)
    
    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):
        return reverse('customerservice:customer-detail-with-agent', kwargs={'pk': self.object.pk})
        # return reverse('customerservice:customer-detail-with-agent', kwargs={'pk': self.object.pk})
        
        
    
# class CustomerCreateView(CreateView):
#     form_class = CustomerForm
#     template_name = 'customer_form.html'
    
#     def get_context_data(self,  **kwargs):
#         context = super(CustomerCreateView, self).get_context_data(**kwargs)
#         context['agent_formset'] = AgentInlineFormset()
#         return context
    
#     def post(self, request, *args, **kwargs):
#         self.object = None
#         form_class = self.get_form_class()
#         form = self.get_form(form_class)
#         agent_formset = AgentInlineFormset(self.request.POST)
#         if form.is_valid() and agent_formset.is_valid():
#             return self.form_valid(form, agent_formset)
#         else:
#             return self.form_invalid(form, agent_formset)
        
#     def form_valid(self, form, agent_formset):
#         self.object = form.save(commit=False)
#         self.object.save()
#         # saving Agent Instances
#         agent = agent_formset.save(commit=False)
#         for meta in agent:
#             meta.customer = self.object
#             meta.save()
#         return redirect(reverse('customerservice:customers'))
#     def form_invalid(self, form, agent_formset):
#         return self.render_to_response(
#             self.get_context_data(form=form,agent_formset=agent_formset))    
        
    

customerservice/templates/agent_form.html
{% extends 'base.html' %}


{% block content %}


<h1>افزودن نماینده</h1>
<form action='' method='post'>
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type='submit' value='افزودن' />
</form>
{% endblock %}

customerservice/templates/base.html
<!DOCTYPE html>
<html lang = "fa-IR" dir="rtl">
        <head>
        {% block title %}<title>مدیریت ارتباط با مشتری</title>{% endblock title %}
        <meta charset = 'utf-8'>
        <meta name = 'viewport' content = 'width=device-width, initial-scale=1'>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.rtl.min.css" integrity="sha384-OXTEbYDqaX2ZY/BOaZV/yFGChYHtrXH2nyXJ372n2Y8abBhrqacCEe+3qhSHtLjy" crossorigin="anonymous">

        {% load static %}
        
        {% comment %} <link rel = 'stylesheet' href = "{% static 'customerservice/styles.css'%} "> {% endcomment %}
        <link rel = 'stylesheet' href = "{% static 'styles.css'%} ">
        <link rel = 'stylesheet' media = 'screen and (max-width:678px)' href = "{% static 'mobile.css'%} ">
        </head>
    <body>
        <nav id = 'navbar' class="bg-white">
            
                <img src = '/static/logo.jpg' width='160' length='70' href='www.afranet.ir'></img>
                <a id = 'maintitle'>مدیریت ارتباط با مشتری</a>
                <ul>
                    
                        {% if user.is_authenticated %}
                    <li><a>کاربر: {{user.get_username}}</a></li>
                    <li><a href = "{% url 'logout'  %}?next={{request.path}}">خروج</a></li>
                        {% else %}
                    <li><a href = "{% url 'login'  %}?next={{request.path}}">ورود</a></li>
                        {% endif %} 
                </ul>
        </nav>
        <hr>
        <div class = 'container-fluid'>
            <div class = 'row'>
                <div class = 'col-sm-2'>
                    {% comment %} {% block sidbar %} {% endcomment %}
                    <div class= 'sidebar-nav'>
                    <ul>
                        <li><a href = '/admin/'>صفحه مدیریت</a></li>
                        <li><a href = "{% url 'customerservice:index' %}">داشبورد</a></li>
                        <li><a href = "{% url 'customerservice:customers' %}">لیست مشترکین</a></li>
                        {% if user.is_authenticated %}
                        <li>کاربر: {{user.get_username}}</li>
                        <li><a href = "{% url 'logout'  %}?next={{request.path}}">خروج</a></li>
                        {% else %}
                        <li><a href = "{% url 'login'  %}?next={{request.path}}">ورود</a></li>
                        {% endif %}
                    </ul>
                    {% comment %} {% endblock %} {% endcomment %}
                    </div>
                </div>
                <div class = 'col-sm-10'>
                    {% block content %}{% endblock content %}
                </div>
            </div>
        </div>
       <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    </body>
</html>

customerservice/templates/base_generic.html
<!DOCTYPE html>
<html>
    <head>
        {% block title %}<title>My CRM</title>{% endblock title %}
        <meta charset = 'utf-8'>
        <meta name = 'viewport' content = 'width=device-width, initial-scale=1'>
        <link rel = 'stylesheet' href = 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>
        <script src = 'https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js'></script>
        <script src = 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></script>

        {% load static %}
        {% comment %} <link rel = 'stylesheet' href = "{% static 'customerservice/styles.css'%} "> {% endcomment %}
        <link rel = 'stylesheet' href = "{% static 'styles.css'%} ">
    </head>
<body>

{% comment %} <h1>Welcome</h1> {% endcomment %}


<div class = 'container-fluid'>
    <div class = 'row'>
        <div class = 'col-sm-2'>
            {% block sidebar %}
            <ul>
                <li><a href = '/admin/'>Admin Page</a></li>
                {% comment %} <li><a href = "{% url 'customers' %}">All Customers</a></li> {% endcomment %}
                {% comment %} <li><a href = "customers/">All Customers</a></li> {% endcomment %}
                
                <li><a href = "">All Services</a></li>
            </ul>
            {% endblock sidebar %}
        </div>
        <div class = 'col-sm-10'>
            {% block content %}{% endblock content %}
        </div>
    </div>
</div>
</body>
</html>

customerservice/templates/customer_agents_edit.html
{% extends 'base.html' %}
{% block content %}

<h1>افزودن نماینده</h1>
<form action='' method='post' enctype='multipart/form-data'>

    {% for hidden_field in form.hidden_fields %}
    {{hidden_field.errors}}
    {{hidden_field}}
    {% endfor %}

    {% csrf_token %}
    {{form.management_form}}
    {{form.non_form_errors}}
    <h3>به روزرسانی نمایندگان:</h3>
    {%for agent_form in form.forms %}
    <hr>
    <h5>
    {%if agent_form.instance.id%}
       مشخصات نماینده: {{agent_form.instance.name}}
    {%else%}
    {% if form.forms|length > 1 %}
        افزودن نماینده دیگر
    {%else%}
        افزودن یک نماینده
    {% endif %}
    {% endif %}
    </h5>

    {% for hidden_field in agent_form.hidden_fields %}
    {{ hidden_field.errors}}
    {% endfor %}
    <table>
        {{agent_form.as_table}}
    </table>
    {% endfor %}
    <hr>
    <p><button type='submit' value='به روزرسانی' class = 'btn btn-primary w-100 mb-3'>به روزرسانی</button></p>
    <a href = '{{ agent.get_absolute_url }}' role='button' class = 'btn btn-primary w-100'>انصراف</a>
    {% comment %} <table>
        {{form.as_table}}
    </table>
    <input type='submit' value='افزودن' /> {% endcomment %}
</form>
{% endblock %}

customerservice/templates/customer_detail.html
{% extends 'base.html' %}


{% block content %}
<h1>اطلاعات مشتریان:</h1>
{%if customer %}
<ul>
    <li>
        <p>{{customer.brand }}</p>
    </li>
    <li>
        {% comment %} {% for  in  %}
        <p>{{customer.brand }}</p>
        {% endfor %} {% endcomment %}
    </li>
</ul>
{% else %}
<p>No Customer!</p>
{% endif %}
{% endblock %}

customerservice/templates/customer_details_with_agent.html
{% extends 'base.html' %}


{% block content %}
<h1>اطلاعات کامل مشتریان:</h1>
{%if customer %}
<ul>
    <li>
        <p>{{customer.brand }}</p>
    </li>
    {% for x in agent %}
    <li>
        <p>{{x.name }}</p>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>هنوز مشتری ای تعریف نشده است!</p>
{% endif %}
<a href = "{% url 'customerservice:customer_agent_edit' pk=customer.pk %}" >ویرایش اطلاعات مشتری</a>
{% comment %} <a href = "customer/(?P<pk>[0-9]+)/agents/edit/" >ویرایش اطلاعات مشتری</a> {% endcomment %}
{% comment %} <a href = "{{x.get_absolute_url }}" >ویرایش اطلاعات مشتری</a> {% endcomment %}
{% endblock %}

customerservice/templates/customer_form.html
{% extends 'base.html' %}


{% block content %}


<h1>افزودن مشتری</h1>
<form action='' method='post'>
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type='submit' value='افزودن' />
</form>
{% endblock %}

customerservice/templates/customer_list.html
{% extends 'base.html' %}


{% block content %}
<h1>لیست مشتریان:</h1>
<a href = "{% url 'customerservice:customer_create' %}" >افزودن مشترک</a>
<a href = "{% url 'customerservice:agent_create' %}" >افزودن نماینده</a>
{%if customer_list%}
<ul>
    {% for x in customer_list%}
    {% comment %} <li>Name of Customer:{{x.name}}</li> {% endcomment %}
    <li>
        {% comment %} <p> Customersss</p> {% endcomment %}
        <a href = "{{x.get_absolute_url }}">{{x.commercialname}}</a>({{x.brand}})
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No Customer!</p>
{% endif %}
{% endblock %}

customerservice/templates/index.html
{% extends 'base.html' %}
{% comment %} {% extends 'customerservice/base_generic.html' %} {% endcomment %}


{% block content %}
<h1 class = 'titr m-30' >داشبورد</h1>
<ul>
    <li>تعداد کل مشترکین: {{num_customer}}</li>
    <li>تعداد کل نمایندگان فنی: {{num_agent}}</li>
</ul>
{% endblock %}